---
- name: restart_sshd
  service:
    name: sshd
    state: restarted

- name: restart_httpd
  service:
    name: httpd
    state: restarted

- name: restart_nginx
  service:
    name: nginx
    state: restarted

- name: reload_networkmanager
  service:
    name: NetworkManager
    state: reloaded

- name: regenerate_auditd_rules
  command: /sbin/augenrules

- name: reload_chrony
  systemd:
    name: "{{ chrony_service_name }}"
    state: restarted
  listen: "chrony service restart"

- name: restart_gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when | bool
