---
# Creates the first monitoring server
# Reccommended specs
# CPU: 2 cores
# Memory: 2GB
# Storage: a piece of string
- name: Install Prometheus
  hosts: monitoringserver
  become: true

  pre_tasks:
    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        msg: "/etc/no-ansible exists - skipping run on this node"
    - name: Install SELinux packages
      package:
        name: python3-policycoreutils.noarch
        state: present

  role:
    - role: cloudalchemy.prometheus
    - role: cloudalchemy.alertmanager

  post_tasks:
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root

- name: Install Prometheus Node Exporter
  hosts: all
  become: true

  pre_tasks:
    - name: Install SELinux packages
      package:
        name: python3-policycoreutils.noarch
        state: present

  roles:
    - role: cloudalchemy.node-exporter
      state: present

  post_tasks:
    - name: Open firewall for node-exporter
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: yes
        state: enabled
